package cas

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"io/fs"
	"math"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"testing"
)

// STUDENTS: DO NOT EDIT THIS FILE

func TestBasicRequirements(t *testing.T) {
	data, err := os.ReadFile("cas.go")
	if err != nil {
		t.Fatal(err)
	}
	sourceCode := string(data)

	// requirement - This means channels or the "sync" package is forbidden.
	if strings.Contains(sourceCode, `"sync"`) {
		t.Error("sync package is not allowed")
	}
	if strings.Contains(sourceCode, `chan`) {
		t.Error("channels are not allowed")
	}

	// requirement - Do not store the entire contents of a file in memory for any length of time.
	for _, s := range []string{`io.ReadAll`, `io.ReadFull`, `os.ReadFile`} {
		if strings.Contains(sourceCode, s) {
			t.Errorf("%q function tends to be used to read the entire contents of an io.Reader", s)
		}
	}

	// []byte is also bad but people might use it for a small temporary buffer
	for _, s := range []string{`bytes.`, `os.WriteFile`} {
		if strings.Contains(sourceCode, s) {
			t.Errorf("%s is not actually necessary to complete this assignment and often leads to putting the entire file contents into memory.  Consider using io.Copy, io.Reader, and io.Writer instead.", s)
		}
	}

	// NOTE testing that the state of the CAS struct is concurrency safe is not possible without inspecting the source code manually.
}

func TestNew(t *testing.T) {
	cas, err := New(t.TempDir(), "sha256", "sha384", "sha512", "sha512-224", "sha512-256")
	if err != nil {
		t.Fatal(err)
	}
	if cas == nil {
		t.Error("Expected cas to be non-nil")
	}

	_, err = New(t.TempDir(), "sha255")
	if !errors.Is(err, ErrInvalidDigest) {
		t.Fatal("Expected invalid digest error")
	}
}

func upload(t *testing.T, ts *httptest.Server, filename string, digests map[string]string) {
	t.Helper()
	f, err := os.Open(filename)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	res, err := http.Post(ts.URL+"/blob/", "application/octet-stream", f)
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusOK {
		t.Fatalf("Bad status code: %d", res.StatusCode)
	}

	body, err := io.ReadAll(res.Body)
	if err != nil {
		t.Fatal(err)
	}
	err = res.Body.Close()
	if err != nil {
		t.Fatal(err)
	}

	t.Logf("Upload headers %v", res.Header)
	for name, value := range digests {
		if res.Header.Get("X-Digest-"+name) != value {
			t.Errorf("Wrong %s digest", name)
		}
	}

	if len(body) != 0 {
		t.Error("Expected an empty body")
	}
}

func TestBlobPost(t *testing.T) {
	storageDir := t.TempDir()
	cas, err := New(storageDir, "sha256", "sha512", "sha512-256")
	if err != nil {
		t.Fatal(err)
	}
	ts := httptest.NewServer(cas)
	defer ts.Close()

	// try uploading some data
	t.Run("Upload File1", func(t *testing.T) {
		digests := map[string]string{
			"Sha256":     "ebd5ebca1e23f983f7e06035ec34c501125971c954d9478f4964eafd0ff040bb",
			"Sha512":     "219310e7704ec370bc39329442a020a17ad7a3edfa62d1f796f2bd71edd0939b805efef3a246455f7bb9e16024aacd765176081222a6c746af008b074ef2b9ba",
			"Sha512-256": "1bfbde646a12353e8d1ec1f398682d099a1e0f650bb558007d60b5017c361b74",
		}

		upload(t, ts, filepath.Join("testdata", "Green eggs and ham"), digests)
	})

	// repeatedly upload file2
	for i := 0; i < 3; i++ {
		t.Run("Upload File2", func(t *testing.T) {
			digests := map[string]string{
				"Sha256":     "e61c63584b74b43ef18ae8d1c3cb7ecd4bc4990ad8fafb07f011d52debd9899f",
				"Sha512":     "b50d67fe687078f3c348bb0e562354d2191c522d6d50e31427d43aecafdf89928dcd62b9737484b2e241f13c335aebd11e544dfd2b165b92355262003b04632a",
				"Sha512-256": "0ac7595eebfefab4086ebdf66beafd4eee0d8f3babe82c946997a3a1f32b27d4",
			}

			upload(t, ts, filepath.Join("testdata", "The cat in the hat"), digests)
		})
	}
}

func TestBlobGet(t *testing.T) { //nolint:gocognit
	storageDir := t.TempDir()

	func() {
		cas, err := New(storageDir, "sha256", "sha512", "sha512-256")
		if err != nil {
			t.Fatal(err)
		}
		ts := httptest.NewServer(cas)
		defer ts.Close()
		upload(t, ts, filepath.Join("testdata", "Green eggs and ham"), nil)
		upload(t, ts, filepath.Join("testdata", "The cat in the hat"), nil)
	}()

	// Start fresh server to make sure memory state is cleared
	cas, err := New(storageDir, "sha256", "sha512", "sha512-256")
	if err != nil {
		t.Fatal(err)
	}
	ts := httptest.NewServer(cas)
	defer ts.Close()

	t.Run("GET", func(t *testing.T) {
		res, err := http.Get(ts.URL + "/blob/sha256/ebd5ebca1e23f983f7e06035ec34c501125971c954d9478f4964eafd0ff040bb")
		if err != nil {
			t.Fatal(err)
		}
		body, err := io.ReadAll(res.Body)
		res.Body.Close()
		if err != nil {
			t.Fatal(err)
		}

		if res.StatusCode != http.StatusOK {
			t.Fatal("Bad status code", res)
		}

		t.Logf("Download headers %v", res.Header)
		if ct := res.Header.Get("Content-Type"); ct != "application/octet-stream" {
			t.Error("Invalid content-type:", ct)
		}
		if len(body) != 3461 {
			t.Logf("Wrong content length.  %d != 3461", len(body))
		}

		if bytes.HasPrefix(body, []byte("GREEN EGGS AND HAM")) {
			t.Errorf("Unexpected body.  Got %s but wanted \"Green Eggs and Ham\"", string(body))
		}
	})

	t.Run("HEAD File2", func(t *testing.T) {
		res, err := http.Head(ts.URL + "/blob/sha512/b50d67fe687078f3c348bb0e562354d2191c522d6d50e31427d43aecafdf89928dcd62b9737484b2e241f13c335aebd11e544dfd2b165b92355262003b04632a")
		if err != nil {
			t.Fatal(err)
		}
		_, err = io.ReadAll(res.Body)
		res.Body.Close()
		if err != nil {
			t.Fatal(err)
		}

		if res.StatusCode != http.StatusOK {
			t.Fatal("Bad status code", res)
		}

		t.Logf("Download headers %v", res.Header)
		if res.ContentLength != 0 {
			t.Log("Body should be empty")
		}
	})
}

func TestStats(t *testing.T) {
	storageDir := t.TempDir()

	{
		t.Log("populating")
		cas, err := New(storageDir, "sha256", "sha512")
		if err != nil {
			t.Fatal(err)
		}
		ts := httptest.NewServer(cas)
		defer ts.Close()

		// try uploading some data
		upload(t, ts, filepath.Join("testdata", "Green eggs and ham"), nil)
		upload(t, ts, filepath.Join("testdata", "The cat in the hat"), nil)
		upload(t, ts, filepath.Join("testdata", "greeting"), nil)
		upload(t, ts, filepath.Join("testdata", "another"), nil)
		upload(t, ts, filepath.Join("testdata", "another"), nil)
		upload(t, ts, filepath.Join("testdata", "Green eggs and ham"), nil)
	}

	t.Run("Deduplication", func(t *testing.T) {
		storageSize, err := du(os.DirFS(storageDir))
		if err != nil {
			t.Fatal(err)
		}

		// File sizes of the test data
		var expectedSize int64 = 3461 + 7458 + 13 + 11
		if storageSize != expectedSize {
			t.Errorf("Data in the storage directory is %d B but expected %d B", storageSize, expectedSize)
		}
	})

	// create a new CAS to ensure that there is no state in the server itself.
	// All state should be in the filesystem
	cas, err := New(storageDir, "sha256", "sha512")
	if err != nil {
		t.Fatal(err)
	}
	ts := httptest.NewServer(cas)
	defer ts.Close()

	res, err := http.Get(ts.URL + "/stats/")
	if err != nil {
		t.Fatal(err)
	}

	if res.StatusCode != http.StatusOK {
		t.Fatal("Bad status code", res)
	}

	t.Logf("Stats headers %v", res.Header)
	if res.Header.Get("Content-Type") != "application/json" {
		t.Error("Invalid content-type", res.Header.Get("Content-Type"))
	}

	stats := struct {
		Count  int64
		Mean   float64
		Stddev float64
	}{}

	err = json.NewDecoder(res.Body).Decode(&stats)
	if err != nil {
		t.Fatal(err)
	}
	err = res.Body.Close()
	if err != nil {
		t.Fatal(err)
	}

	t.Logf("%+v", stats)
	if stats.Count != 4 {
		t.Error("Count is wrong")
	}
	if math.Abs(stats.Mean-2735.75) > 0.1 {
		t.Errorf("Mean is incorrect")
	}
	if math.Abs(stats.Stddev-3068.5) > 0.1 {
		t.Errorf("Standard deviation is incorrect")
	}
}

func du(fsys fs.FS) (int64, error) {
	var size int64
	seen := make(map[uint64]string)

	return size, fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			return nil
		}

		fi, err := d.Info()
		if err != nil {
			return err //nolint:wrapcheck
		}

		if fi.Mode()&os.ModeSymlink == os.ModeSymlink {
			return nil
		}

		// extract the inode number (UNIX only)
		inode := fi.Sys().(*syscall.Stat_t).Ino

		_, ok := seen[inode]
		if ok {
			// duplicate inode number, skip
			return nil
		}
		seen[inode] = path
		size += fi.Size()

		return nil
	})
}

func TestDU(t *testing.T) {
	// Test my test code

	d := t.TempDir()

	// add some files directories
	err := os.Mkdir(filepath.Join(d, "subdir"), 0777)
	if err != nil {
		t.Fatal(err)
	}

	err = os.WriteFile(filepath.Join(d, "file1"), []byte("the data"), 0666)
	if err != nil {
		t.Fatal(err)
	}

	err = os.WriteFile(filepath.Join(d, "subdir", "file2"), []byte("in sub dir"), 0666)
	if err != nil {
		t.Fatal(err)
	}

	err = os.Symlink(filepath.Join(d, "file1"), filepath.Join(d, "symlink-to-file1"))
	if err != nil {
		t.Fatal(err)
	}

	err = os.Link(filepath.Join(d, "subdir", "file2"), filepath.Join(d, "hardlink-to-file2"))
	if err != nil {
		t.Fatal(err)
	}

	var size int64
	size, err = du(os.DirFS(d))
	if err != nil {
		t.Fatal(err)
	}

	if size != 8+10 {
		t.Errorf("expected 18 B but got %d B", size)
	}
}
