name: Testing Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  test:
    name: Test
    runs-on: ud-vdi-arc
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: stable
        cache: false
    - name: Run all our unit tests and benchmarks
      run: go test -v -timeout 2s ./...

  golangci:
    name: Lint
    runs-on: ud-vdi-arc
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  # TODO ensure only the proper files are modified (git diff main feedback)