// Package main is the CLI for the CAS system.
package main

import (
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"

	"assignment-cas/pkg/cas"
)

// STUDENTS: DO NOT EDIT THIS FILE

func main() {
	if len(os.Args) != 2 {
		log.Fatal("Usage: cas STORAGE-DIR")
	}

	app, err := cas.New(os.Args[1], "sha256", "sha512")
	if err != nil {
		log.Fatal(err)
	}

	addr := "localhost:3333"
	fmt.Printf("Listening on http://%s\n", addr)

	err = http.ListenAndServe(addr, app)
	if errors.Is(err, http.ErrServerClosed) {
		log.Println("server closed")
	} else if err != nil {
		log.Fatalf("error starting server: %s\n", err)
	}
}
