name: Testing Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: stable
        cache: false

    - name: Run Unit Tests
      run: go test -v -timeout 2s ./...
    
    - name: Run CLI Tests
      run: |-
        make test-cli

    # - name: Output Results
    #   if: success() || failure()
    #   run: cat test.out
    
    # - name: Grade tests
    #   if: success() || failure()
    #   run: ./rubric.sh test.out

  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
